"use client";

import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { theme } from "@/lib/theme";

/**
 * Landing page for a stakeholder's one-time invite link
 * (`/portal/accept-invite?token=...`, generated by
 * POST /api/entities/:id/stakeholders/:stakeholderId/portal-invite and copied/sent by
 * an admin — see that route's doc comment). Public per `src/middleware.ts`'s
 * PUBLIC_PATHS — there's no session of any kind yet at this point.
 *
 * ALWAYS shows a password field: this component has no way to know in advance whether
 * the invited person already has a StakeholderUser account with a password set (from
 * accepting an earlier invite at a different company) — POST /api/portal/accept-invite
 * itself decides whether the submitted password is actually needed/used (see that
 * route's doc comment) and simply logs the person in either way. Framing the field as
 * optional-looking would be more confusing than harmless to fill in and have ignored.
 */
export default function AcceptInvitePage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const token = searchParams.get("token") ?? "";

  const [password, setPassword] = useState("");
  const [status, setStatus] = useState<"idle" | "loading" | "error">("idle");
  const [message, setMessage] = useState<string | null>(null);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setStatus("loading");
    setMessage(null);
    try {
      const res = await fetch("/api/portal/accept-invite", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token, password }),
      });
      const data = await res.json();
      if (!res.ok) {
        setStatus("error");
        setMessage(data.error ?? "Couldn't accept this invite.");
        return;
      }
      router.push("/portal");
      router.refresh();
    } catch (err) {
      setStatus("error");
      setMessage(err instanceof Error ? err.message : "Couldn't accept this invite.");
    }
  }

  if (!token) {
    return (
      <main style={{ fontFamily: theme.font.body, padding: "2rem", maxWidth: 400, margin: "0 auto" }}>
        <h1 style={{ fontFamily: theme.font.heading }}>Missing invite link</h1>
        <p style={{ color: theme.inkMuted }}>
          This page needs the full link from your invite email or message — it looks like the <code>token</code>{" "}
          part is missing. Ask the company for the link again if you don't still have it.
        </p>
      </main>
    );
  }

  return (
    <main style={{ fontFamily: theme.font.body, padding: "2rem", maxWidth: 400, margin: "0 auto" }}>
      <h1 style={{ fontFamily: theme.font.heading }}>Set up your account</h1>
      <p style={{ color: theme.inkMuted }}>
        Choose a password to finish setting up access to your holdings. If you've already set one up for another
        company on this platform, it'll be reused automatically and this field is ignored.
      </p>
      <form onSubmit={handleSubmit}>
        <label style={labelStyle}>
          Password
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            minLength={8}
            autoFocus
            style={inputStyle}
          />
        </label>
        <p style={{ color: theme.inkMuted, fontSize: "0.8rem", margin: "0.25rem 0 0.75rem" }}>At least 8 characters.</p>
        <button type="submit" disabled={status === "loading"} style={buttonStyle}>
          {status === "loading" ? "Setting up…" : "Continue"}
        </button>
        {message && <p style={{ color: theme.danger.fg, marginTop: "0.5rem" }}>{message}</p>}
      </form>
    </main>
  );
}

const buttonStyle: React.CSSProperties = {
  padding: "0.5rem 1rem",
  border: "none",
  borderRadius: 6,
  background: theme.primary,
  color: theme.onPrimary,
  fontWeight: 600,
  cursor: "pointer",
};
const labelStyle: React.CSSProperties = { display: "block", margin: "0.75rem 0", fontSize: "0.9rem", color: theme.ink };
const inputStyle: React.CSSProperties = {
  display: "block",
  width: "100%",
  padding: "0.5rem 0.6rem",
  marginTop: "0.3rem",
  border: `1px solid ${theme.border}`,
  borderRadius: 6,
  background: theme.surface,
  color: theme.ink,
};
